name: K6 Load Test 
on: [push]
permissions:
  contents: write

jobs:
  build: 
    name: K6 Load Test
    runs-on: ubuntu-latest
    steps:
      - name: Step 1 - Checkout
        uses: actions/checkout@v3

      - name: Step 2 - Run K6 Load Test
        uses: grafana/k6-action@v0.2.0
        with: #informando o arquivo
          filename: mao_na_massa/exemplo1.js
      
      - run: ls & mkdir report & mv index.html report

      - name: Step 3 - Upload Artifact
        uses: actions/upload-artifact@v3
        with: #nome para o artefato de saída
          name: Relatório de testes de performance
          path: report

      - name: Step 4 - Publish Report
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: report